name: Node CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Compile
        run: npm run compile

      # Use unit rather than test to skip the pretest step, as that would duplicate steps above.
      - name: Unit tests
        run: npm run test:unit
        env:
          CI: true
